### ISSUE TITLE
Bug: matchExact for namespace selection is not filtering targets correctly

### ISSUE THREAD

**Issue by giselacb** [achetronic/hitman#5]
**Description**
The matchExact option in the target configuration for namespace selection is not working as expected. When specified, it's not filtering the targets and instead captures all namespaces.

**Current Behavior**
When configuring a target with matchExact for namespace selection, the agent processes PipelineRuns from all namespaces instead of only the specified one.

**Expected Behavior**
The agent should only process PipelineRuns from the exact namespace specified in the configuration.

**Configuration Used**
```
target:
  group: tekton.dev
  version: v1
  resource: pipelineruns
  name: 
    matchRegex: ".*"
  namespace:
    matchExact: "centralpayments"
```
**Workaround**

Currently using matchRegex with exact pattern match as a temporary solution:
```
namespace:
  matchRegex: "^namespace-name$"
```
